<?php

namespace AppModelBundle\Entity;

/**
 * NivelEducativoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelEducativoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
