<?php

namespace AppModelBundle\Entity;

/**
 * NivelEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelEducativoRepository extends \Doctrine\ORM\EntityRepository
{
}
