<?php

namespace AppModelBundle\Entity;

/**
 * ProcesoJuridicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoJuridicoRepository extends \Doctrine\ORM\EntityRepository
{
}
