<?php

namespace AppModelBundle\Entity;

/**
 * ProcesoJuridicoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoJuridicoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
