<?php

namespace AppModelBundle\Entity;

/**
 * ProteccionSeguridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProteccionSeguridadRepository extends \Doctrine\ORM\EntityRepository
{
}
