<?php

namespace AppModelBundle\Entity;

/**
 * TipoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
