<?php

namespace AppModelBundle\Entity;

/**
 * TipoTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
