<?php

namespace AppModelBundle\Entity;

/**
 * TipoProcesoJuridicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProcesoJuridicoRepository extends \Doctrine\ORM\EntityRepository
{
}
