app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
select_causales:
    path:     /causales
    defaults: { _controller: AppBundle:Ajax:causales }
    options:
        expose: true
    
select_clases:
    path:     /clases
    defaults: { _controller: AppBundle:Ajax:clases }
    options:
        expose: true

